Repository apigee/apigee-m10n-drupal, pull requests merged in 2021-04, with the labels that each got.

#258 Switching logic between Edge and Apigee X for user menu
  .circleci/RoboFile.php
  src/Controller/PrepaidBalanceController.php
  src/Controller/PricingAndPlansController.php
  src/Entity/ListBuilder/PurchasedPlanListBuilder.php
  src/Entity/ListBuilder/PurchasedPlanListBuilderForDeveloper.php
  src/EventSubscriber/ValidateMonetizationEnabledSubscriber.php
  src/Monetization.php
  src/MonetizationInterface.php
Labels: cla: yes

#268 Initial Commit for NGMint (ApigeeX 5G)
  apigee_m10n.libraries.yml
  config/install/core.entity_view_display.xproduct.xproduct.default.yml
  config/install/core.entity_view_display.xrate_plan.xrate_plan.default.yml
  css/apigee_m10n.apigex-plan-list.css
  src/Controller/BuyApiController.php
  src/Entity/Access/XRatePlanAccessControlHandler.php
  src/Entity/Access/XRatePlanSubscriptionAccessHandler.php
  src/Entity/ListBuilder/XProductListBuilder.php
  src/Entity/Property/ApiXProductPropertyAwareDecoratorTrait.php
  src/Entity/Property/BillingPeriodPropertyAwareDecoratorTrait.php
  src/Entity/Property/ConsumptionPricingTypePropertyAwareDecoratorTrait.php
  src/Entity/Property/CurrencyCodePropertyAwareDecoratorTrait.php
  src/Entity/Property/FixedFeeFrequencyPropertyAwareDecoratorTrait.php
  src/Entity/Property/PaymentFundingModelPropertyAwareDecoratorTrait.php
  src/Entity/Property/RevenueShareTypePropertyAwareDecoratorTrait.php
  src/Entity/Property/XPackagePropertyAwareDecoratorTrait.php
  src/Entity/Storage/Controller/XProductEntityControllerProxy.php
  src/Entity/Storage/Controller/XProductEntityControllerProxyInterface.php
  src/Entity/Storage/Controller/XRatePlanSdkControllerProxy.php
  src/Entity/Storage/Controller/XRatePlanSdkControllerProxyInterface.php
  src/Entity/Storage/XProductStorage.php
  src/Entity/Storage/XProductStorageInterface.php
  src/Entity/Storage/XRatePlanStorage.php
  src/Entity/Storage/XRatePlanStorageInterface.php
  src/Entity/XProduct.php
  src/Entity/XProductInterface.php
  src/Entity/XRatePlan.php
  src/Entity/XRatePlanInterface.php
  src/Form/RatePlanXConfigForm.php
  src/Plugin/Field/FieldFormatter/ConsumptionPricingRatesFormatter.php
  src/Plugin/Field/FieldFormatter/FixedRecurringFeeFormatter.php
  src/Plugin/Field/FieldFormatter/RatePlanXFeeFormatter.php
  src/Plugin/Field/FieldFormatter/RevenueShareRatesFormatter.php
  src/Plugin/Field/FieldType/ConsumptionPricingRatesFieldItem.php
  src/Plugin/Field/FieldType/FixedRecurringFeeFieldItem.php
  src/Plugin/Field/FieldType/RatePlanXFeeFieldItem.php
  src/Plugin/Field/FieldType/RevenueShareRatesFieldItem.php
  src/Plugin/Menu/PlansPluginClass.php
  src/Plugin/Menu/ProductPluginClass.php
  src/Plugin/Menu/RatePlanPluginClass.php
  templates/apigee-entity--xproduct.html.twig
  templates/apigee-entity--xrate-plan.html.twig
  templates/rate-plan-consumption-rates.html.twig
  templates/rate-plan-fixed-recurringfee.html.twig
  templates/rate-plan-revenue-rates.html.twig
  templates/rate-plan-xfee.html.twig
  tests/src/Kernel/Access/AccessKernelTest.php
Labels: cla: yes, enhancement

#269 Resolves Kernel test case issues
  apigee_m10n.routing.yml
  tests/src/Kernel/MonetizationServiceKernelTest.php
Labels: cla: yes

#270 Resolved functional testcase
  modules/apigee_m10n_add_credit/tests/src/Functional/AddCreditFunctionalTestBase.php
  modules/apigee_m10n_add_credit/tests/src/FunctionalJavascript/AddCreditFunctionalJavascriptTestBase.php
Labels: cla: yes

#271 ApigeeX BuyApi menu tooltip fix- 5G
  src/Plugin/Menu/PlansPluginClass.php
Labels: bug, cla: yes, enhancement

#274 Update required version of apigee_client_php and apigee_edge
  composer.json
Labels: cla: yes

#275 Update required version of apigee_client_php and apigee_edge
  composer.json
Labels: cla: yes

#276 Update composer.json
  composer.json
Labels: cla: yes
